name: Publish Package to npm

on:
  release:
    types: [published] # سيعمل السكريبت تلقائياً بمجرد نشر Release جديد على جيتهاب

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # 1. جلب الكود من المستودع
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. إعداد بيئة Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # أو أي إصدار تعتمده لمشروعك
          registry-url: 'https://registry.npmjs.org'

      # 3. تثبيت الاعتماديات (Dependencies)
      - name: Install dependencies
        run: pnpm ci

      # 4. بناء المشروع (إذا كانت مكتبتك تحتاج إلى ترجمة أو Build مثل TypeScript)
      - name: Build package
        run: pnpm build

      # 5. النشر إلى npm
      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.ACTIONS_IMAGES_TRACKER }}